baseURL = "https://torehanpena.github.io/"
title = "Pena"
paginate = 5
theme = "hugo-ink"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false 
buildExpired = false
googleAnalytics = "UA-XXXXXX"


[params]
env = "production"