baseURL = "https://torehanpena.github.io/"
title = "Torehan Pena"
paginate = 40
theme = "hugo-ink"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false 
buildExpired = false
googleAnalytics = "UA-XXXXXX"


copyright = "© Haturnuhun"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "ink-demo"

[params]
env = "production"
	subtitle = "Kliping, Reportase dari masa ke masa (https://torehanpena.github.io)"

	# Optional 64x64 avatar image.
	avatar = "https://miro.medium.com/fit/c/262/262/1*7yslpgKWZyLnE0S9HDPZpQ.jpeg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	# mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Kumpulan Tulisan"
url = "/"
weight = 1


[[menu.main]]
name = "Tentang Penulis"
url = "/penulis"
weight = 3

[[menu.main]]
name = "Perjalanan"
url = "/masa"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/torehanpena"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"



